Add tags to iam users
Cox-Automotive/alks.js pull request #303
Opened 2022-10-23 03:56 UTC by elliottzack429

# Description

Adds tags to createAccessKeys.  Adds new functions updateIamUser and getIamUser. 

Rally # [US878015](https://rally1.rallydev.com/#/?detail=/userstory/642939499993&fdp=true): ALKS JS - Enable tagging for IAM Users

## Type of change

_Please remove options that are not relevant._

- [X] Feature (non-breaking change which adds functionality)

# How has this been tested?

## Steps:
  1. Unit Tests

2022-10-24 15:02 UTC, americk0 reviewed
Just one thing. The rest looks good

2022-10-24 15:03 UTC, americk0 requested changes
Sorry I meant to hit "request changes" not "comment"

2022-10-24 15:12 UTC, elliottzack429 commented on src/alks.ts
>    };
Yep missed that one thanks!  Fix pushed

2022-10-25 14:48 UTC, americk0 approved these changes

2022-10-25 14:50 UTC, merged